name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-15, windows-latest]
        include:
          - os: ubuntu-22.04
            target: linux
            core-platform: linux
            core-arch: x86_64
          - os: macos-15
            target: macos
            core-platform: macos
            core-arch: aarch64
          - os: windows-latest
            target: windows
            core-platform: windows
            core-arch: x86_64

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Download Fungi Artifacts
        shell: bash
        run: |
          scripts/fetch_core_artifacts.sh --platform "${{ matrix.core-platform }}" --arch "${{ matrix.core-arch }}"

      - name: Install Linux Dependencies
        if: matrix.target == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libayatana-appindicator3-dev protobuf-compiler

      - name: Install macOS Dependencies
        if: matrix.target == 'macos'
        run: |
          brew untap aws/tap || true
          brew install protobuf

      - name: Install Windows Dependencies
        if: matrix.target == 'windows'
        run: |
          choco install protoc
        shell: powershell

      - name: Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          flutter-version: '3.44.6'
          channel: 'stable'
          cache: true

      - name: Install Pub Dependencies
        run: flutter pub get

      - name: Generate gRPC Code
        shell: bash
        run: |
          # Install protoc_plugin
          dart pub global activate protoc_plugin 21.1.2
          export PATH="$PATH:$HOME/.pub-cache/bin"
          
          # Generate
          protoc --dart_out=grpc:lib/src/grpc/generated -Ifungi-artifacts fungi-artifacts/fungi_daemon.proto

      - name: Analyze
        run: flutter analyze

      # - name: Run Tests
      #   run: flutter test
